// Generated by CoffeeScript 1.6.3
(function() {
  var _this = this;

  describe('VectorReader', function() {
    var baseImageData;
    baseImageData = {
      width: 1,
      height: 1,
      data: [0, 0, 0, 0]
    };
    return describe('readVectorAt', function() {
      var imageData, reader;
      reader = null;
      imageData = null;
      beforeEach(function() {
        reader = new VectorReader;
        return imageData = _.extend({}, baseImageData);
      });
      it('can read zero movement', function() {
        var vector;
        imageData.data = [0, 0, 0, 0];
        vector = reader.readVectorAt(0, 0, imageData);
        assert.equal(vector.x, 0);
        return assert.equal(vector.y, 0);
      });
      return it('can read max negative x', function() {
        var vector;
        imageData.data = [0, 0, 255, 0];
        vector = reader.readVectorAt(0, 0, imageData);
        assert.equal(vector.x, -1.0);
        return assert.equal(vector.y, 0);
      });
    });
  });

}).call(this);

/*
//@ sourceMappingURL=VectorReader.spec.map
*/
