// Generated by CoffeeScript 1.6.3
(function() {
  var _this = this;

  describe('VectorReader', function() {
    return describe('readVectorAt', function() {
      it('can read zero movement', function() {
        var imageData, reader, vector;
        reader = new VectorReader;
        imageData = {
          width: 1,
          height: 1,
          data: [0, 0, 0, 0]
        };
        vector = reader.readVectorAt(0, 0, imageData);
        assert.equal(vector.x, 0);
        return assert.equal(vector.y, 0);
      });
      return it('can read max negative x', function() {
        var imageData, reader, vector;
        reader = new VectorReader;
        imageData = {
          width: 1,
          height: 1,
          data: [0, 0, 255, 0]
        };
        vector = reader.readVectorAt(0, 0, imageData);
        assert.equal(vector.x, -1.0);
        return assert.equal(vector.y, 0);
      });
    });
  });

}).call(this);

/*
//@ sourceMappingURL=VectorReader.spec.map
*/
