// Generated by CoffeeScript 1.6.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  (function(doc, nav) {
    var Ball, detect, draw, initialize, _saveContextProperties,
      _this = this;
    Ball = (function() {
      function Ball(x, y) {
        this.x = x;
        this.y = y;
        this._clamp = __bind(this._clamp, this);
        this.readOffset = __bind(this.readOffset, this);
        this.gradient = __bind(this.gradient, this);
        this.draw = __bind(this.draw, this);
        this.radius = 50;
      }

      Ball.prototype.draw = function(context) {
        context.beginPath();
        context.arc(this.x, this.y, this.radius, 0, 2 * Math.PI, false);
        context.fillStyle = this.gradient(context);
        return context.fill();
      };

      Ball.prototype.gradient = function(context) {
        var gradient;
        gradient = context.createLinearGradient(this.x - this.radius, this.y - this.radius, this.radius * 2, this.radius * 2);
        gradient.addColorStop(0, "black");
        gradient.addColorStop(1, "white");
        return gradient;
      };

      Ball.prototype.readOffset = function(imageData) {
        var changed, g, nextX, nextY, pos, r, scale, velocityX, velocityY;
        pos = ((this.y * imageData.width) + this.x) * 4;
        r = imageData.data[pos];
        g = imageData.data[pos + 1];
        scale = 16;
        velocityX = Math.floor((r - 128) / scale);
        velocityY = Math.floor((g - 128) / scale);
        nextX = this._clamp(this.x + velocityX, 0, imageData.width - 1);
        nextY = this._clamp(this.y + velocityY, 0, imageData.height - 1);
        changed = !(nextX === this.x && nextY === this.y);
        this.x = nextX;
        this.y = nextY;
        return changed;
      };

      Ball.prototype._clamp = function(value, min, max) {
        return Math.min(max, Math.max(min, value));
      };

      return Ball;

    })();
    detect = function() {
      return initialize();
    };
    initialize = function() {
      var i;
      console.log("Starting");
      _this.canvas = doc.getElementById("balls");
      _this.width = canvas.width;
      _this.height = canvas.height;
      _this.context = canvas.getContext("2d");
      _this.balls = (function() {
        var _i, _results;
        _results = [];
        for (i = _i = 0; _i <= 5; i = ++_i) {
          _results.push(new Ball(Math.floor(Math.random() * width), Math.floor(Math.random() * height)));
        }
        return _results;
      })();
      _this.dirty = true;
      draw();
      return console.log("Started");
    };
    draw = function() {
      var imageData, saved;
      if (_this.dirty) {
        saved = _saveContextProperties(_this.context);
        _this.p = 100;
        _this.size = 100;
        _this.context.fillStyle = _this.context.createLinearGradient(_this.p, _this.p, _this.p + _this.size, _this.p + _this.size);
        _this.context.fillStyle.addColorStop(0, "black");
        _this.context.fillStyle.addColorStop(1, "white");
        _this.context.fillRect(_this.p, _this.p, _this.size, _this.size);
        _this.context.fillStyle = "red";
        _this.context.fillRect(_this.p, _this.p, 5, 5);
        _this.context.fillRect(_this.p + _this.size, _this.p + _this.size, 5, 5);
        imageData = _this.context.getImageData(0, 0, _this.width, _this.height);
        saved.restore();
      }
      return requestAnimationFrame(draw);
    };
    _saveContextProperties = function(context) {
      var fillStyle, globalCompositeOperation;
      globalCompositeOperation = context.globalCompositeOperation;
      fillStyle = context.fillStyle;
      return {
        restore: function() {
          _this.context.globalCompositeOperation = globalCompositeOperation;
          return _this.context.fillStyle = fillStyle;
        }
      };
    };
    return addEventListener("DOMContentLoaded", detect);
  })(document, navigator);

}).call(this);

/*
//@ sourceMappingURL=main.map
*/
