// Generated by CoffeeScript 1.6.3
(function() {
  var VectorReader,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  VectorReader = (function() {
    function VectorReader(maxMagnitude) {
      this.maxMagnitude = maxMagnitude != null ? maxMagnitude : 10;
      this._interpretAsVelocity = __bind(this._interpretAsVelocity, this);
      this.readVectorAt = __bind(this.readVectorAt, this);
    }

    VectorReader.prototype.readVectorAt = function(x, y, imageData) {
      var a, b, g, pos, r, velocityX, velocityY;
      pos = ((y * imageData.width) + x) * 4;
      r = imageData.data[pos];
      g = imageData.data[pos + 1];
      b = imageData.data[pos + 2];
      a = imageData.data[pos + 3];
      velocityX = this._interpretAsVelocity(r, b);
      velocityY = this._interpretAsVelocity(g, a);
      console.log("" + r + "," + g + "," + b + "," + a + " -> " + velocityX + "," + velocityY);
      return {
        x: velocityX,
        y: velocityY
      };
    };

    VectorReader.prototype._interpretAsVelocity = function(positive, negative) {
      var scale,
        _this = this;
      scale = function(value) {
        return (value / 255.0) * _this.maxMagnitude;
      };
      return Math.ceil(scale(positive)) - Math.ceil(scale(negative));
    };

    return VectorReader;

  })();

  window.VectorReader = VectorReader;

}).call(this);

/*
//@ sourceMappingURL=VectorReader.map
*/
